### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by hornos** [pm2-hive/pm2-webshell#1]
npm ERR! Command failed: git clone --template=/home/.../.npm/_git-remotes/_templates --mirror ssh://git@github.com/Unitech/tty.js.git /home/.../.npm/_git-remotes/ssh-git-github-com-Unitech-tty-js-git-9211673b
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     http://github.com/npm/npm/issues

Mirror should be https://github.com/Unitech/tty.js.git ?

**Comment by Unitech** [comment]
new version published thx
