### ISSUE TITLE
Shell prompt flash and disappear (black screen)

### ISSUE THREAD

**Issue by hgneng** [pm2-hive/pm2-webshell#4]
I can see the shell prompt flash for less than one second and disappear. Then the browser leave me a black screen and nothing response.
Reproduce site: http://www.eguidedog.net:8080/, acount foo/bar
I have opened TCP 8080 in amazon security group. It's a Ubuntu 14.04 server.

Any idea?

**Comment by Slind14** [comment]
try without browser plugins. Firefox and chromes works fine for me after disabling plugins which change website content.

**Comment by yidinghan** [comment]
in my mac, either firefox developer edition, firefox, chrome and safari work, all of them was 'see the shell prompt flash for less than one second and disappear'.
i also test it in incognito window, it didn't work too.

**Comment by vforsh** [comment]
I've exact same problem. I've tried with all browser plugins disabled - no luck :(

**Comment by Unitech** [comment]
Fixed

**Comment by brodeuralexis** [comment]
The same things happened to me.

I found this while digging in the logs :

```
pm2-webshell-0 Error: forkpty(3) failed.
pm2-webshell-0     at new Terminal (/home/abrodeur/.pm2/node_modules/pty.js/lib/pty.js:122:14)
pm2-webshell-0     at Function.Terminal.fork.Terminal.spawn.Terminal.createTerminal (/home/abrodeur/.pm2/node_modules/pty.js/lib/pty.js:187:10)
pm2-webshell-0     at Session.handleCreate (/home/abrodeur/.pm2/node_modules/tty.js/lib/tty.js:447:14)
pm2-webshell-0     at Socket.<anonymous> (/home/abrodeur/.pm2/node_modules/tty.js/lib/tty.js:189:20)
pm2-webshell-0     at Socket.emit [as $emit] (events.js:106:17)
pm2-webshell-0     at SocketNamespace.handlePacket (/home/abrodeur/.pm2/node_modules/socket.io/lib/namespace.js:335:22)
pm2-webshell-0     at Manager.onClientMessage (/home/abrodeur/.pm2/node_modules/socket.io/lib/manager.js:488:38)
pm2-webshell-0     at WebSocket.Transport.onMessage (/home/abrodeur/.pm2/node_modules/socket.io/lib/transport.js:387:20)
pm2-webshell-0     at Parser.<anonymous> (/home/abrodeur/.pm2/node_modules/socket.io/lib/transports/websocket/hybi-16.js:39:10)
pm2-webshell-0     at Parser.emit (events.js:95:17)
```

**Comment by FredericLatour** [comment]
I'm having the same problem.
I installed Firefox with no extensions at all. It didn't change anything.
Any idea?
